--- #YAML:1.0
name:                Acme-Anything
version:             0.01
abstract:            Anything, even non-existant modules are loadable
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Josh ben Jore <jjore@cpan.org>
